vim.keymap.set('n', '<leader>Gi', '<cmd>Git<cr>')
vim.keymap.set('n', '<leader>Gb', '<cmd>Git blame<cr>')
vim.keymap.set('n', '<leader>Gl', '<cmd>Git log<cr>')
vim.keymap.set('n', '<leader>Gd', '<cmd>Git diff<cr>')
vim.keymap.set('n', '<leader>Gw', '<cmd>Gwrite | Git commit<cr>')
vim.keymap.set('n', '<leader>Gp', '<cmd>Git push<cr>')
vim.keymap.set('n', '<leader>Ge', '<cmd>Git add -p %<cr>')
vim.keymap.set('n', '<leader>GVV', '<cmd>GV<cr>')
vim.keymap.set('n', '<leader>GV!', '<cmd>GV!<cr>')
vim.keymap.set('n', '<leader>GV?', '<cmd>GV?<cr>')
