return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    branch = "main",
    build = ":TSUpdate",
    opts = {
        auto_install = true,
        sync_install = true,
        highlight = { enable = true },
        ensure_installed = {
            "bash",
            "blade", -- for Laravel blade files
            "c",
            "css",
            "scss",
            "comment",
            "elixir",
            "git_config",
            "gitcommit",
            "gitignore",
            "go",
            "graphql",
            "html",
            "http",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "php",
            "phpdoc",
            "python",
            "query",
            "regex",
            "sql",
            "svelte",
            "tsx",
            "typescript",
            "vim",
            "vimdoc",
            "vue",
            "yaml",
        },
    },
}
